import { NutritionItem } from "../../types";

export const mockNutritionDataArray: NutritionItem[] = [
  {
    id: 'chicken-lettuce-wraps',
    category: 'appetizers',
    name: 'Chicken Lettuce Wraps',
    servings: 2,
    calories: 330,
    calsFromFat: 120,
    fat: '13g',
    saturatedFat: '3g',
    transFat: '0g',
    cholesterol: '15mg',
    sodium: '920mg',
    carbohydrates: '33g',
    fiber: '4g',
    sugar: '14g',
    protein: '19g'
  },
  {
    id: 'chili-garlic-green-beans',
    category: 'appetizers',
    name: 'Chili Garlic Green Beans',
    servings: 2,
    calories: 260,
    calsFromFat: 180,
    fat: '20g',
    saturatedFat: '3g',
    transFat: '0g',
    cholesterol: '0mg',
    sodium: '850mg',
    carbohydrates: '19g',
    fiber: '5g',
    sugar: '12g',
    protein: '4g'
  },
  {
    id: 'crispy-green-beans',
    category: 'appetizers',
    name: 'Crispy Green Beans',
    servings: 2,
    calories: 500,
    calsFromFat: 350,
    fat: '39g',
    saturatedFat: '6g',
    transFat: '0g',
    cholesterol: '10mg',
    sodium: '750mg',
    carbohydrates: '35g',
    fiber: '4g',
    sugar: '6g',
    protein: '4g'
  },
  {
    id: 'edamame',
    category: 'appetizers',
    name: 'Edamame',
    servings: 2,
    calories: 200,
    calsFromFat: 80,
    fat: '8g',
    saturatedFat: '1.5g',
    transFat: '0g',
    cholesterol: '0mg',
    sodium: '980mg',
    carbohydrates: '12g',
    fiber: '6g',
    sugar: '0g',
    protein: '18g'
  },
  {
    id: 'tempura-calamari',
    category: 'appetizers',
    name: 'Tempura Calamari',
    servings: 2,
    calories: 380,
    calsFromFat: 150,
    fat: '29g',
    saturatedFat: '4.5g',
    transFat: '2g',
    cholesterol: '75mg',
    sodium: '820mg',
    carbohydrates: '22g',
    fiber: '2g',
    sugar: '5g',
    protein: '10g'
  },
  {
    id: 'pork-dumplings-pan-fried',
    category: 'appetizers',
    name: 'Pork Dumplings Pan Fried',
    servings: 6,
    calories: 90,
    calsFromFat: 45,
    fat: '5g',
    saturatedFat: '1.5g',
    transFat: '0g',
    cholesterol: '10mg',
    sodium: '230mg',
    carbohydrates: '7g',
    fiber: '0g',
    sugar: '2g',
    protein: '3g'
  },
  {
    id: 'pork-dumplings-steamed',
    category: 'appetizers',
    name: 'Pork Dumplings Steamed',
    servings: 6,
    calories: 80,
    calsFromFat: 30,
    fat: '3.5g',
    saturatedFat: '1g',
    transFat: '0g',
    cholesterol: '10mg',
    sodium: '230mg',
    carbohydrates: '7g',
    fiber: '0g',
    sugar: '2g',
    protein: '3g'
  },
  {
    id: 'shrimp-dumplings-pan-fried',
    category: 'appetizers',
    name: 'Shrimp Dumplings Pan Fried',
    servings: 6,
    calories: 60,
    calsFromFat: 25,
    fat: '2.5g',
    saturatedFat: '0g',
    transFat: '0g',
    cholesterol: '30mg',
    sodium: '270mg',
    carbohydrates: '6g',
    fiber: '0g',
    sugar: '2g',
    protein: '4g'
  },
  {
    id: 'shrimp-dumplings-steamed',
    category: 'appetizers',
    name: 'Shrimp Dumplings Steamed',
    servings: 6,
    calories: 50,
    calsFromFat: 10,
    fat: '1g',
    saturatedFat: '0g',
    transFat: '0g',
    cholesterol: '30mg',
    sodium: '270mg',
    carbohydrates: '6g',
    fiber: '0g',
    sugar: '2g',
    protein: '4g'
  },
  {
    id: 'pork-egg-rolls',
    category: 'appetizers',
    name: 'Pork Egg Rolls',
    servings: 2,
    calories: 350,
    calsFromFat: 170,
    fat: '19g',
    saturatedFat: '3.5g',
    transFat: '0g',
    cholesterol: '25mg',
    sodium: '460mg',
    carbohydrates: '34g',
    fiber: '3g',
    sugar: '7g',
    protein: '9g'
  },
  {
    id: 'vegetable-spring-rolls',
    category: 'appetizers',
    name: 'Vegetable Spring Rolls',
    servings: 3,
    calories: 240,
    calsFromFat: 110,
    fat: '12g',
    saturatedFat: '2g',
    transFat: '0g',
    cholesterol: '0mg',
    sodium: '280mg',
    carbohydrates: '30g',
    fiber: '1g',
    sugar: '8g',
    protein: '3g'
  },
  {
    id: 'egg-drop-soup-bowl',
    category: 'soups',
    name: 'Egg Drop Soup Bowl',
    servings: 4,
    calories: 70,
    calsFromFat: 15,
    fat: '1.5g',
    saturatedFat: '0g',
    transFat: '0g',
    cholesterol: '45mg',
    sodium: '940mg',
    carbohydrates: '11g',
    fiber: '0g',
    sugar: '4g',
    protein: '2g'
  },
  {
    id: 'egg-drop-soup-cup',
    category: 'soups',
    name: 'Egg Drop Soup Cup',
    servings: 1,
    calories: 40,
    calsFromFat: 10,
    fat: '1g',
    saturatedFat: '0g',
    transFat: '0g',
    cholesterol: '60mg',
    sodium: '560mg',
    carbohydrates: '6g',
    fiber: '0g',
    sugar: '2g',
    protein: '1g'
  },
  {
    id: 'hot-sour-soup-bowl',
    category: 'soups',
    name: 'Hot & Sour Soup Bowl',
    servings: 4,
    calories: 120,
    calsFromFat: 30,
    fat: '3g',
    saturatedFat: '0.5g',
    transFat: '0g',
    cholesterol: '50mg',
    sodium: '930mg',
    carbohydrates: '15g',
    fiber: '1g',
    sugar: '2g',
    protein: '7g'
  },
  {
    id: 'hot-sour-soup-cup',
    category: 'soups',
    name: 'Hot & Sour Soup Cup',
    servings: 1,
    calories: 70,
    calsFromFat: 15,
    fat: '2g',
    saturatedFat: '0g',
    transFat: '0g',
    cholesterol: '30mg',
    sodium: '580mg',
    carbohydrates: '9g',
    fiber: '0g',
    sugar: '1g',
    protein: '4g'
  },
  {
    id: 'spicy-chicken-soup-bowl',
    category: 'soups',
    name: 'Spicy Chicken Soup Bowl',
    servings: 6,
    calories: 170,
    calsFromFat: 15,
    fat: '2g',
    saturatedFat: '0g',
    transFat: '0g',
    cholesterol: '20mg',
    sodium: '1310mg',
    carbohydrates: '30g',
    fiber: '1g',
    sugar: '6g',
    protein: '9g'
  },
  {
    id: 'spicy-chicken-soup-cup',
    category: 'soups',
    name: 'Spicy Chicken Soup Cup',
    servings: 1,
    calories: 170,
    calsFromFat: 15,
    fat: '2g',
    saturatedFat: '0g',
    transFat: '0g',
    cholesterol: '20mg',
    sodium: '1310mg',
    carbohydrates: '30g',
    fiber: '1g',
    sugar: '6g',
    protein: '9g'
  },
  {
    id: 'wonton-soup-bowl',
    category: 'soups',
    name: 'Wonton Soup Bowl',
    servings: 4,
    calories: 120,
    calsFromFat: 30,
    fat: '3.5g',
    saturatedFat: '1g',
    transFat: '0g',
    cholesterol: '40mg',
    sodium: '740mg',
    carbohydrates: '13g',
    fiber: '1g',
    sugar: '3g',
    protein: '10g'
  },
  {
    id: 'wonton-soup-cup',
    category: 'soups',
    name: 'Wonton Soup Cup',
    servings: 1,
    calories: 130,
    calsFromFat: 30,
    fat: '3.5g',
    saturatedFat: '1g',
    transFat: '0g',
    cholesterol: '35mg',
    sodium: '770mg',
    carbohydrates: '14g',
    fiber: '1g',
    sugar: '2g',
    protein: '9g'
  },
  {
    id: 'beef-broccoli',
    category: 'main-entree',
    name: 'Beef with Broccoli',
    servings: 2,
    calories: 330,
    calsFromFat: 140,
    fat: '15g',
    saturatedFat: '4.5g',
    transFat: '0g',
    cholesterol: '30mg',
    sodium: '1150mg',
    carbohydrates: '24g',
    fiber: '2g',
    sugar: '16g',
    protein: '26g'
  },
  {
    id: 'crispy-honey-shrimp',
    category: 'main-entree',
    name: 'Crispy Honey Shrimp',
    servings: 2,
    calories: 510,
    calsFromFat: 250,
    fat: '28g',
    saturatedFat: '4g',
    transFat: '0g',
    cholesterol: '170mg',
    sodium: '590mg',
    carbohydrates: '40g',
    fiber: '0g',
    sugar: '19g',
    protein: '23g'
  },
  {
    id: 'ginger-chicken-broccoli',
    category: 'main-entree',
    name: 'Ginger Chicken with Broccoli',
    servings: 2,
    calories: 240,
    calsFromFat: 60,
    fat: '7g',
    saturatedFat: '1.5g',
    transFat: '0g',
    cholesterol: '55mg',
    sodium: '650mg',
    carbohydrates: '15g',
    fiber: '3g',
    sugar: '10g',
    protein: '30g'
  },
  {
    id: 'kung-pao-chicken',
    category: 'main-entree',
    name: 'Kung Pao Chicken',
    servings: 2,
    calories: 520,
    calsFromFat: 310,
    fat: '34g',
    saturatedFat: '6g',
    transFat: '0g',
    cholesterol: '40mg',
    sodium: '960mg',
    carbohydrates: '15g',
    fiber: '3g',
    sugar: '10g',
    protein: '27g'
  },
  {
    id: 'kung-pao-shrimp',
    category: 'main-entree',
    name: 'Kung Pao Shrimp',
    servings: 2,
    calories: 510,
    calsFromFat: 310,
    fat: '35g',
    saturatedFat: '6g',
    transFat: '0g',
    cholesterol: '85mg',
    sodium: '1630mg',
    carbohydrates: '27g',
    fiber: '4g',
    sugar: '10g',
    protein: '24g'
  },
  {
    id: 'ma-po-tofu',
    category: 'main-entree',
    name: 'Ma Po Tofu',
    servings: 2,
    calories: 590,
    calsFromFat: 270,
    fat: '31g',
    saturatedFat: '4.5g',
    transFat: '0g',
    cholesterol: '0mg',
    sodium: '1390mg',
    carbohydrates: '33g',
    fiber: '8g',
    sugar: '15g',
    protein: '29g'
  },
  {
    id: 'mongolian-beef',
    category: 'main-entree',
    name: 'Mongolian Beef',
    servings: 2,
    calories: 380,
    calsFromFat: 170,
    fat: '19g',
    saturatedFat: '6g',
    transFat: '0g',
    cholesterol: '40mg',
    sodium: '1240mg',
    carbohydrates: '21g',
    fiber: '1g',
    sugar: '15g',
    protein: '31g'
  },
  {
    id: 'orange-chicken',
    category: 'main-entree',
    name: 'Orange Chicken',
    servings: 2,
    calories: 640,
    calsFromFat: 340,
    fat: '37g',
    saturatedFat: '6g',
    transFat: '0g',
    cholesterol: '25mg',
    sodium: '670mg',
    carbohydrates: '54g',
    fiber: '3g',
    sugar: '25g',
    protein: '22g'
  },
  {
    id: 'salt-pepper-prawns',
    category: 'main-entree',
    name: 'Salt & Pepper Prawns',
    servings: 2,
    calories: 460,
    calsFromFat: 300,
    fat: '34g',
    saturatedFat: '11g',
    transFat: '0g',
    cholesterol: '125mg',
    sodium: '1490mg',
    carbohydrates: '22g',
    fiber: '3g',
    sugar: '6g',
    protein: '18g'
  },
  {
    id: 'sweet-sour-chicken',
    category: 'main-entree',
    name: 'Sweet & Sour Chicken',
    servings: 2,
    calories: 440,
    calsFromFat: 190,
    fat: '21g',
    saturatedFat: '3.5g',
    transFat: '0g',
    cholesterol: '60mg',
    sodium: '280mg',
    carbohydrates: '44g',
    fiber: '2g',
    sugar: '23g',
    protein: '18g'
  },
  {
    id: 'beef-broccoli-bowl',
    category: 'bowls',
    name: 'Beef with Broccoli',
    servings: 1,
    calories: 390,
    calsFromFat: 150,
    fat: '17g',
    saturatedFat: '5g',
    transFat: '0g',
    cholesterol: '30mg',
    sodium: '1600mg',
    carbohydrates: '34g',
    fiber: '3g',
    sugar: '24g',
    protein: '26g'
  },
  {
    id: 'crispy-honey-shrimp-bowl',
    category: 'bowls',
    name: 'Crispy Honey Shrimp',
    servings: 1,
    calories: 700,
    calsFromFat: 380,
    fat: '42g',
    saturatedFat: '7g',
    transFat: '0g',
    cholesterol: '60mg',
    sodium: '1250mg',
    carbohydrates: '59g',
    fiber: '3g',
    sugar: '38g',
    protein: '15g'
  },
  {
    id: 'ginger-chicken-broccoli-bowl',
    category: 'bowls',
    name: 'Ginger Chicken with Broccoli',
    servings: 1,
    calories: 350,
    calsFromFat: 90,
    fat: '10g',
    saturatedFat: '2g',
    transFat: '0g',
    cholesterol: '60mg',
    sodium: '1450mg',
    carbohydrates: '31g',
    fiber: '3g',
    sugar: '24g',
    protein: '34g'
  },
  {
    id: 'kung-pao-chicken-bowl',
    category: 'bowls',
    name: 'Kung Pao Chicken',
    servings: 1,
    calories: 590,
    calsFromFat: 350,
    fat: '39g',
    saturatedFat: '7g',
    transFat: '0g',
    cholesterol: '45mg',
    sodium: '1290mg',
    carbohydrates: '19g',
    fiber: '3g',
    sugar: '13g',
    protein: '29g'
  },
  {
    id: 'kung-pao-shrimp-bowl',
    category: 'bowls',
    name: 'Kung Pao Shrimp',
    servings: 1,
    calories: 450,
    calsFromFat: 280,
    fat: '31g',
    saturatedFat: '5g',
    transFat: '0g',
    cholesterol: '55mg',
    sodium: '1660mg',
    carbohydrates: '27g',
    fiber: '4g',
    sugar: '13g',
    protein: '19g'
  },
  {
    id: 'mongolian-beef-bowl',
    category: 'bowls',
    name: 'Mongolian Beef',
    servings: 1,
    calories: 360,
    calsFromFat: 180,
    fat: '17g',
    saturatedFat: '5g',
    transFat: '0g',
    cholesterol: '35mg',
    sodium: '1320mg',
    carbohydrates: '23g',
    fiber: '1g',
    sugar: '18g',
    protein: '27g'
  },
  {
    id: 'orange-chicken-bowl',
    category: 'bowls',
    name: 'Orange Chicken',
    servings: 1,
    calories: 670,
    calsFromFat: 310,
    fat: '34g',
    saturatedFat: '5g',
    transFat: '0g',
    cholesterol: '105mg',
    sodium: '1010mg',
    carbohydrates: '55g',
    fiber: '3g',
    sugar: '31g',
    protein: '34g'
  },
  {
    id: 'sweet-sour-chicken-bowl',
    category: 'bowls',
    name: 'Sweet & Sour Chicken',
    servings: 1,
    calories: 710,
    calsFromFat: 360,
    fat: '40g',
    saturatedFat: '7g',
    transFat: '0g',
    cholesterol: '25mg',
    sodium: '410mg',
    carbohydrates: '68g',
    fiber: '4g',
    sugar: '33g',
    protein: '22g'
  },
  {
    id: 'fried-rice-combo',
    category: 'fried-rice-noodles',
    name: 'Fried Rice Combo',
    servings: 2,
    calories: 550,
    calsFromFat: 120,
    fat: '13g',
    saturatedFat: '3.5g',
    transFat: '0g',
    cholesterol: '145mg',
    sodium: '1030mg',
    carbohydrates: '77g',
    fiber: '2g',
    sugar: '9g',
    protein: '28g'
  },
  {
    id: 'fried-rice-beef',
    category: 'fried-rice-noodles',
    name: 'Fried Rice with Beef',
    servings: 2,
    calories: 540,
    calsFromFat: 130,
    fat: '15g',
    saturatedFat: '4g',
    transFat: '0g',
    cholesterol: '110mg',
    sodium: '950mg',
    carbohydrates: '78g',
    fiber: '2g',
    sugar: '9g',
    protein: '23g'
  },
  {
    id: 'fried-rice-chicken',
    category: 'fried-rice-noodles',
    name: 'Fried Rice with Chicken',
    servings: 2,
    calories: 510,
    calsFromFat: 90,
    fat: '10g',
    saturatedFat: '2g',
    transFat: '0g',
    cholesterol: '125mg',
    sodium: '880mg',
    carbohydrates: '76g',
    fiber: '2g',
    sugar: '9g',
    protein: '27g'
  },
  {
    id: 'fried-rice-pork',
    category: 'fried-rice-noodles',
    name: 'Fried Rice with Pork',
    servings: 2,
    calories: 550,
    calsFromFat: 130,
    fat: '15g',
    saturatedFat: '4g',
    transFat: '0g',
    cholesterol: '125mg',
    sodium: '870mg',
    carbohydrates: '76g',
    fiber: '2g',
    sugar: '9g',
    protein: '25g'
  },
  {
    id: 'fried-rice-shrimp',
    category: 'fried-rice-noodles',
    name: 'Fried Rice with Shrimp',
    servings: 2,
    calories: 460,
    calsFromFat: 70,
    fat: '8g',
    saturatedFat: '1.5g',
    transFat: '0g',
    cholesterol: '155mg',
    sodium: '1110mg',
    carbohydrates: '76g',
    fiber: '2g',
    sugar: '9g',
    protein: '18g'
  },
  {
    id: 'fried-rice-vegetable',
    category: 'fried-rice-noodles',
    name: 'Fried Rice with Vegetables',
    servings: 2,
    calories: 450,
    calsFromFat: 70,
    fat: '8g',
    saturatedFat: '1.5g',
    transFat: '0g',
    cholesterol: '95mg',
    sodium: '770mg',
    carbohydrates: '81g',
    fiber: '4g',
    sugar: '11g',
    protein: '12g'
  },
  {
    id: 'short-rib-fried-rice',
    category: 'fried-rice-noodles',
    name: 'Short Rib Fried Rice',
    servings: 2,
    calories: 590,
    calsFromFat: 150,
    fat: '18g',
    saturatedFat: '6g',
    transFat: '0g',
    cholesterol: '130mg',
    sodium: '990mg',
    carbohydrates: '76g',
    fiber: '2g',
    sugar: '12g',
    protein: '27g'
  },
  {
    id: 'korean-glass-noodles-combo',
    category: 'fried-rice-noodles',
    name: 'Korean Glass Noodles Combo',
    servings: 2,
    calories: 660,
    calsFromFat: 210,
    fat: '23g',
    saturatedFat: '4.5g',
    transFat: '0g',
    cholesterol: '185mg',
    sodium: '1400mg',
    carbohydrates: '97g',
    fiber: '3g',
    sugar: '27g',
    protein: '22g'
  },
  {
    id: 'korean-glass-noodles-chicken',
    category: 'fried-rice-noodles',
    name: 'Korean Glass Noodles with Chicken',
    servings: 2,
    calories: 630,
    calsFromFat: 180,
    fat: '18g',
    saturatedFat: '2.5g',
    transFat: '0g',
    cholesterol: '155mg',
    sodium: '1400mg',
    carbohydrates: '97g',
    fiber: '3g',
    sugar: '27g',
    protein: '21g'
  },
  {
    id: 'korean-glass-noodles-beef',
    category: 'fried-rice-noodles',
    name: 'Korean Glass Noodles with Beef',
    servings: 2,
    calories: 670,
    calsFromFat: 200,
    fat: '17g',
    saturatedFat: '3.5g',
    transFat: '0g',
    cholesterol: '145mg',
    sodium: '1400mg',
    carbohydrates: '97g',
    fiber: '3g',
    sugar: '27g',
    protein: '17g'
  },
  {
    id: 'korean-glass-noodles-vegetable',
    category: 'fried-rice-noodles',
    name: 'Korean Glass Noodles with Vegetables',
    servings: 2,
    calories: 600,
    calsFromFat: 80,
    fat: '11g',
    saturatedFat: '1g',
    transFat: '0g',
    cholesterol: '115mg',
    sodium: '1400mg',
    carbohydrates: '99g',
    fiber: '5g',
    sugar: '24g',
    protein: '12g'
  },
  {
    id: 'pad-thai-combo',
    category: 'fried-rice-noodles',
    name: 'Combo Pad Thai',
    servings: 2,
    calories: 750,
    calsFromFat: 240,
    fat: '27g',
    saturatedFat: '5g',
    transFat: '0g',
    cholesterol: '235mg',
    sodium: '1790mg',
    carbohydrates: '98g',
    fiber: '3g',
    sugar: '27g',
    protein: '29g'
  },
  {
    id: 'pad-thai-chicken',
    category: 'fried-rice-noodles',
    name: 'Chicken Pad Thai',
    servings: 2,
    calories: 740,
    calsFromFat: 230,
    fat: '25g',
    saturatedFat: '5g',
    transFat: '0g',
    cholesterol: '215mg',
    sodium: '1610mg',
    carbohydrates: '97g',
    fiber: '3g',
    sugar: '27g',
    protein: '32g'
  },
  {
    id: 'pad-thai-shrimp',
    category: 'fried-rice-noodles',
    name: 'Shrimp Pad Thai',
    servings: 2,
    calories: 720,
    calsFromFat: 230,
    fat: '25g',
    saturatedFat: '5g',
    transFat: '0g',
    cholesterol: '255mg',
    sodium: '2030mg',
    carbohydrates: '97g',
    fiber: '3g',
    sugar: '27g',
    protein: '28g'
  },
  {
    id: 'signature-lo-mein-combo',
    category: 'fried-rice-noodles',
    name: 'Signature Lo Mein Combo',
    servings: 2,
    calories: 460,
    calsFromFat: 120,
    fat: '13g',
    saturatedFat: '3g',
    transFat: '0g',
    cholesterol: '55mg',
    sodium: '1880mg',
    carbohydrates: '58g',
    fiber: '3g',
    sugar: '12g',
    protein: '28g'
  },
  {
    id: 'signature-lo-mein-beef',
    category: 'fried-rice-noodles',
    name: 'Signature Lo Mein with Beef',
    servings: 2,
    calories: 450,
    calsFromFat: 120,
    fat: '14g',
    saturatedFat: '3.5g',
    transFat: '0g',
    cholesterol: '20mg',
    sodium: '1720mg',
    carbohydrates: '59g',
    fiber: '3g',
    sugar: '12g',
    protein: '22g'
  },
  {
    id: 'signature-lo-mein-chicken',
    category: 'fried-rice-noodles',
    name: 'Signature Lo Mein with Chicken',
    servings: 2,
    calories: 410,
    calsFromFat: 80,
    fat: '9g',
    saturatedFat: '1.5g',
    transFat: '0g',
    cholesterol: '30mg',
    sodium: '1650mg',
    carbohydrates: '57g',
    fiber: '3g',
    sugar: '12g',
    protein: '26g'
  },
  {
    id: 'signature-lo-mein-pork',
    category: 'fried-rice-noodles',
    name: 'Signature Lo Mein with Pork',
    servings: 2,
    calories: 440,
    calsFromFat: 120,
    fat: '13g',
    saturatedFat: '3g',
    transFat: '0g',
    cholesterol: '25mg',
    sodium: '1630mg',
    carbohydrates: '57g',
    fiber: '3g',
    sugar: '12g',
    protein: '22g'
  },
  {
    id: 'signature-lo-mein-shrimp',
    category: 'fried-rice-noodles',
    name: 'Signature Lo Mein with Shrimp',
    servings: 2,
    calories: 380,
    calsFromFat: 80,
    fat: '9g',
    saturatedFat: '1.5g',
    transFat: '0g',
    cholesterol: '60mg',
    sodium: '1980mg',
    carbohydrates: '58g',
    fiber: '3g',
    sugar: '12g',
    protein: '17g'
  },
  {
    id: 'signature-lo-mein-vegetable',
    category: 'fried-rice-noodles',
    name: 'Signature Lo Mein with Vegetables',
    servings: 2,
    calories: 360,
    calsFromFat: 60,
    fat: '7g',
    saturatedFat: '1g',
    transFat: '0g',
    cholesterol: '0mg',
    sodium: '1550mg',
    carbohydrates: '63g',
    fiber: '5g',
    sugar: '14g',
    protein: '11g'
  },
  {
    id: 'singapore-street-noodles',
    category: 'fried-rice-noodles',
    name: 'Singapore Street Noodles',
    servings: 2,
    calories: 610,
    calsFromFat: 60,
    fat: '7g',
    saturatedFat: '1.5g',
    transFat: '0g',
    cholesterol: '50mg',
    sodium: '1460mg',
    carbohydrates: '112g',
    fiber: '3g',
    sugar: '11g',
    protein: '26g'
  },
  {
    id: 'white-rice',
    category: 'side-orders',
    name: 'White Rice 8 oz',
    servings: 1,
    calories: 290,
    calsFromFat: 0,
    fat: '0g',
    saturatedFat: '0g',
    transFat: '0g',
    cholesterol: '0mg',
    sodium: '0mg',
    carbohydrates: '65g',
    fiber: '1g',
    sugar: '1g',
    protein: '5g'
  },
  {
    id: 'brown-rice',
    category: 'side-orders',
    name: 'Brown Rice 8 oz',
    servings: 1,
    calories: 250,
    calsFromFat: 0,
    fat: '0g',
    saturatedFat: '0g',
    transFat: '0g',
    cholesterol: '0mg',
    sodium: '0mg',
    carbohydrates: '53g',
    fiber: '4g',
    sugar: '0g',
    protein: '5g'
  },
  {
    id: 'signature-sauce',
    category: 'side-orders',
    name: 'Signature Sauce 1 oz',
    servings: 1,
    calories: 190,
    calsFromFat: 50,
    fat: '6g',
    saturatedFat: '0g',
    transFat: '0g',
    cholesterol: '0mg',
    sodium: '1520mg',
    carbohydrates: '28g',
    fiber: '0g',
    sugar: '12g',
    protein: '5g'
  },
];