import { NutritionItem } from "../../types";

export const mockNutritionDataArray: NutritionItem[] = [
  {
    id: 'chicken-lettuce-wraps',
    category: 'appetizers',
    name: 'Chicken Lettuce Wraps',
    description: '',
    imgSrc: '',
    servings: 2,
    calories: 330,
    calsFromFat: 120,
    fat: '13g',
    saturatedFat: '3g',
    transFat: '0g',
    cholesterol: '15mg',
    sodium: '920mg',
    carbohydrates: '33g',
    fiber: '4g',
    sugar: '14g',
    protein: '19g',
    dvFat: 0,
    dvSaturatedFat: 0,
    dvCholesterol: 0,
    dvSodium: 0,
    dvCarbohydrates: 0,
    dvFiber: 0,
  },
  {
    id: 'chili-garlic-green-beans',
    category: 'appetizers',
    name: 'Chili Garlic Green Beans',
    description: '',
    imgSrc: '',
    servings: 2,
    calories: 260,
    calsFromFat: 180,
    fat: '20g',
    saturatedFat: '3g',
    transFat: '0g',
    cholesterol: '0mg',
    sodium: '850mg',
    carbohydrates: '19g',
    fiber: '5g',
    sugar: '12g',
    protein: '4g',
    dvFat: 0,
    dvSaturatedFat: 0,
    dvCholesterol: 0,
    dvSodium: 0,
    dvCarbohydrates: 0,
    dvFiber: 0,
  },
  {
    id: 'egg-drop-soup-bowl',
    category: 'soups',
    name: 'Egg Drop Soup Bowl',
    description: '',
    imgSrc: '',
    servings: 4,
    calories: 70,
    calsFromFat: 15,
    fat: '1.5g',
    saturatedFat: '0g',
    transFat: '0g',
    cholesterol: '45mg',
    sodium: '940mg',
    carbohydrates: '11g',
    fiber: '0g',
    sugar: '4g',
    protein: '2g',
    dvFat: 0,
    dvSaturatedFat: 0,
    dvCholesterol: 0,
    dvSodium: 0,
    dvCarbohydrates: 0,
    dvFiber: 0,
  },
  {
    id: 'egg-drop-soup-cup',
    category: 'soups',
    name: 'Egg Drop Soup Cup',
    description: '',
    imgSrc: '',
    servings: 1,
    calories: 40,
    calsFromFat: 10,
    fat: '1g',
    saturatedFat: '0g',
    transFat: '0g',
    cholesterol: '60mg',
    sodium: '560mg',
    carbohydrates: '6g',
    fiber: '0g',
    sugar: '2g',
    protein: '1g',
    dvFat: 0,
    dvSaturatedFat: 0,
    dvCholesterol: 0,
    dvSodium: 0,
    dvCarbohydrates: 0,
    dvFiber: 0,
  },
  {
    id: 'beef-broccoli',
    category: 'main-entree',
    name: 'Beef with Broccoli',
    description: '',
    imgSrc: '',
    servings: 2,
    calories: 330,
    calsFromFat: 140,
    fat: '15g',
    saturatedFat: '4.5g',
    transFat: '0g',
    cholesterol: '30mg',
    sodium: '1150mg',
    carbohydrates: '24g',
    fiber: '2g',
    sugar: '16g',
    protein: '26g',
    dvFat: 0,
    dvSaturatedFat: 0,
    dvCholesterol: 0,
    dvSodium: 0,
    dvCarbohydrates: 0,
    dvFiber: 0,
  },
  {
    id: 'beef-broccoli-bowl',
    category: 'bowls',
    name: 'Beef with Broccoli',
    description: '',
    imgSrc: '',
    servings: 1,
    calories: 390,
    calsFromFat: 150,
    fat: '17g',
    saturatedFat: '5g',
    transFat: '0g',
    cholesterol: '30mg',
    sodium: '1600mg',
    carbohydrates: '34g',
    fiber: '3g',
    sugar: '24g',
    protein: '26g',
    dvFat: 0,
    dvSaturatedFat: 0,
    dvCholesterol: 0,
    dvSodium: 0,
    dvCarbohydrates: 0,
    dvFiber: 0,
  },
  {
    id: 'fried-rice-beef',
    category: 'fried-rice-noodles',
    name: 'Fried Rice with Beef',
    description: '',
    imgSrc: '',
    servings: 2,
    calories: 540,
    calsFromFat: 130,
    fat: '15g',
    saturatedFat: '4g',
    transFat: '0g',
    cholesterol: '110mg',
    sodium: '950mg',
    carbohydrates: '78g',
    fiber: '2g',
    sugar: '9g',
    protein: '23g',
    dvFat: 0,
    dvSaturatedFat: 0,
    dvCholesterol: 0,
    dvSodium: 0,
    dvCarbohydrates: 0,
    dvFiber: 0,
  },
  {
    id: 'white-rice',
    category: 'side-orders',
    name: 'White Rice 8 oz',
    description: '',
    imgSrc: '',
    servings: 1,
    calories: 290,
    calsFromFat: 0,
    fat: '0g',
    saturatedFat: '0g',
    transFat: '0g',
    cholesterol: '0mg',
    sodium: '0mg',
    carbohydrates: '65g',
    fiber: '1g',
    sugar: '1g',
    protein: '5g',
    dvFat: 0,
    dvSaturatedFat: 0,
    dvCholesterol: 0,
    dvSodium: 0,
    dvCarbohydrates: 0,
    dvFiber: 0,
  }
];